// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAu2ayNobNY0_JaDqRRhtxI0T9eGDoIM4',
    appId: '1:462582707865:web:a1b4c748c18e275d982a08',
    messagingSenderId: '462582707865',
    projectId: 'rodriguezriosnathalie',
    authDomain: 'rodriguezriosnathalie.firebaseapp.com',
    storageBucket: 'rodriguezriosnathalie.firebasestorage.app',
    measurementId: 'G-D1L7W23DV7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS9WgvW_wVJGaftjqMfDc8zrv2bueJS9c',
    appId: '1:462582707865:android:bc794488870e0941982a08',
    messagingSenderId: '462582707865',
    projectId: 'rodriguezriosnathalie',
    storageBucket: 'rodriguezriosnathalie.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApN1_iW2ycPLicm1ARkZSoOIa_ob-I4r4',
    appId: '1:462582707865:ios:0b9de10374df02b1982a08',
    messagingSenderId: '462582707865',
    projectId: 'rodriguezriosnathalie',
    storageBucket: 'rodriguezriosnathalie.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApN1_iW2ycPLicm1ARkZSoOIa_ob-I4r4',
    appId: '1:462582707865:ios:0b9de10374df02b1982a08',
    messagingSenderId: '462582707865',
    projectId: 'rodriguezriosnathalie',
    storageBucket: 'rodriguezriosnathalie.firebasestorage.app',
    iosBundleId: 'com.example.examen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAu2ayNobNY0_JaDqRRhtxI0T9eGDoIM4',
    appId: '1:462582707865:web:6b5420713adc31bc982a08',
    messagingSenderId: '462582707865',
    projectId: 'rodriguezriosnathalie',
    authDomain: 'rodriguezriosnathalie.firebaseapp.com',
    storageBucket: 'rodriguezriosnathalie.firebasestorage.app',
    measurementId: 'G-8VC5LK9J3C',
  );
}