import 'package:cloud_firestore/cloud_firestore.dart';

class SeedRestauranteService {
  static final FirebaseFirestore _db = FirebaseFirestore.instance;

  static const String collectionName = 'productos_restaurante';

  static final List<Map<String, dynamic>> productos = [
    {
      'id': 'bife_200gr',
      'nombre': 'Bife 200gr',
      'categoria': 'Bife y lomo al kamado',
      'precio': 35.00,
      'descripcion': 'Bife de 200gr preparado al kamado.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 1,
    },
    {
      'id': 'bife_premium_250gr',
      'nombre': 'Bife premium 250gr',
      'categoria': 'Bife y lomo al kamado',
      'precio': 45.00,
      'descripcion': 'Bife premium de 250gr preparado al kamado.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 2,
    },
    {
      'id': 'bife_pimienta',
      'nombre': 'Bife pimienta',
      'categoria': 'Bife y lomo al kamado',
      'precio': 40.00,
      'descripcion': 'Bife acompañado con salsa a la pimienta.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 3,
    },
    {
      'id': 'bife_champinones',
      'nombre': 'Bife champiñones',
      'categoria': 'Bife y lomo al kamado',
      'precio': 40.00,
      'descripcion': 'Bife acompañado con salsa de champiñones.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 4,
    },
    {
      'id': 'lomo_fino_180gr',
      'nombre': 'Lomo fino 180gr',
      'categoria': 'Bife y lomo al kamado',
      'precio': 35.00,
      'descripcion': 'Lomo fino de 180gr preparado al kamado.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 5,
    },
    {
      'id': 'lomo_fino_250gr',
      'nombre': 'Lomo fino 250gr',
      'categoria': 'Bife y lomo al kamado',
      'precio': 45.00,
      'descripcion': 'Lomo fino de 250gr preparado al kamado.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 6,
    },
    {
      'id': 'lomo_fino_pimienta',
      'nombre': 'Lomo fino pimienta',
      'categoria': 'Bife y lomo al kamado',
      'precio': 40.00,
      'descripcion': 'Lomo fino con salsa a la pimienta.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 7,
    },
    {
      'id': 'lomo_saltado',
      'nombre': 'Lomo saltado',
      'categoria': 'Bife y lomo al kamado',
      'precio': 28.00,
      'descripcion': 'Lomo saltado tradicional.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 8,
    },
    {
      'id': 'pollo_a_la_parrilla',
      'nombre': 'Pollo a la parrilla',
      'categoria': 'Pollo',
      'precio': 20.00,
      'descripcion': 'Pollo a la parrilla.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 9,
    },
    {
      'id': 'pollo_champinones',
      'nombre': 'Pollo champiñones',
      'categoria': 'Pollo',
      'precio': 25.00,
      'descripcion': 'Pollo acompañado con salsa de champiñones.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 10,
    },
    {
      'id': 'milanesa_de_pollo',
      'nombre': 'Milanesa de pollo',
      'categoria': 'Pollo',
      'precio': 16.00,
      'descripcion': 'Milanesa de pollo crocante.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 11,
    },
    {
      'id': 'alitas_maracuya',
      'nombre': 'Alitas maracuyá',
      'categoria': 'Pollo',
      'precio': 18.00,
      'descripcion': 'Alitas bañadas en salsa de maracuyá.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 12,
    },
    {
      'id': 'alitas_bbq',
      'nombre': 'Alitas BBQ',
      'categoria': 'Pollo',
      'precio': 18.00,
      'descripcion': 'Alitas bañadas en salsa BBQ.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 13,
    },
    {
      'id': 'alitas_acevichadas',
      'nombre': 'Alitas acevichadas',
      'categoria': 'Pollo',
      'precio': 18.00,
      'descripcion': 'Alitas con salsa acevichada.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 14,
    },
    {
      'id': 'nuggets',
      'nombre': 'Nuggets',
      'categoria': 'Pollo',
      'precio': 18.00,
      'descripcion': 'Nuggets de pollo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 15,
    },
    {
      'id': 'pollo_saltado',
      'nombre': 'Pollo saltado',
      'categoria': 'Pollo',
      'precio': 23.00,
      'descripcion': 'Pollo saltado estilo criollo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 16,
    },
    {
      'id': 'hamburguesa_clasica',
      'nombre': 'Hamburguesa clásica',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 11.00,
      'descripcion': 'Hamburguesa clásica de la casa.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 17,
    },
    {
      'id': 'hamburguesa_mixta',
      'nombre': 'Hamburguesa mixta',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 14.00,
      'descripcion': 'Hamburguesa mixta.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 18,
    },
    {
      'id': 'hamburguesa_doble',
      'nombre': 'Hamburguesa doble',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 19.00,
      'descripcion': 'Hamburguesa doble.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 19,
    },
    {
      'id': 'hamburguesa_el_barto',
      'nombre': 'Hamburguesa El Barto',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 18.00,
      'descripcion': 'Hamburguesa especial El Barto.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 20,
    },
    {
      'id': 'hamburguesa_crispi',
      'nombre': 'Hamburguesa crispi',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 14.00,
      'descripcion': 'Hamburguesa crispy.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 21,
    },
    {
      'id': 'salchi_huaychulo',
      'nombre': 'Salchi huaychulo',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 14.00,
      'descripcion': 'Salchipapa huaychulo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 22,
    },
    {
      'id': 'salchi_frankfurt',
      'nombre': 'Salchi Frankfurt',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 14.00,
      'descripcion': 'Salchipapa Frankfurt.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 23,
    },
    {
      'id': 'salchi_montada',
      'nombre': 'Salchi montada',
      'categoria': 'Hamburguesas y salchipapas',
      'precio': 15.00,
      'descripcion': 'Salchipapa montada.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 24,
    },
    {
      'id': 'fetuccini_alfredo',
      'nombre': 'Fetuccini al Alfredo',
      'categoria': 'Pastas y pasta con carne',
      'precio': 15.00,
      'descripcion': 'Fetuccini en salsa Alfredo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 25,
    },
    {
      'id': 'fetuccini_champinones',
      'nombre': 'Fetuccini champiñones',
      'categoria': 'Pastas y pasta con carne',
      'precio': 16.00,
      'descripcion': 'Fetuccini con salsa de champiñones.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 26,
    },
    {
      'id': 'fetuccini_bolonesa',
      'nombre': 'Fetuccini boloñesa',
      'categoria': 'Pastas y pasta con carne',
      'precio': 16.00,
      'descripcion': 'Fetuccini con salsa boloñesa.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 27,
    },
    {
      'id': 'fetuccini_saltado_lomo',
      'nombre': 'Fetuccini saltado de lomo',
      'categoria': 'Pastas y pasta con carne',
      'precio': 25.00,
      'descripcion': 'Fetuccini acompañado con saltado de lomo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 28,
    },
    {
      'id': 'fetuccini_huancaina',
      'nombre': 'Fetuccini huancaína',
      'categoria': 'Pastas y pasta con carne',
      'precio': 15.00,
      'descripcion': 'Fetuccini en salsa huancaína.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 29,
    },
    {
      'id': 'lasana_de_carne',
      'nombre': 'Lasaña de carne',
      'categoria': 'Pastas y pasta con carne',
      'precio': 16.00,
      'descripcion': 'Lasaña de carne.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 30,
    },
    {
      'id': 'fetuccini_pesto_lomo_bife',
      'nombre': 'Fetuccini pesto con lomo/bife',
      'categoria': 'Pastas y pasta con carne',
      'precio': 35.00,
      'descripcion': 'Fetuccini al pesto acompañado con lomo o bife.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 31,
    },
    {
      'id': 'fetuccini_huancaina_lomo_bife',
      'nombre': 'Fetuccini huancaína con lomo/bife',
      'categoria': 'Pastas y pasta con carne',
      'precio': 35.00,
      'descripcion': 'Fetuccini en salsa huancaína acompañado con lomo o bife.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 32,
    },
    {
      'id': 'fetuccini_huancaina_lomo_saltado',
      'nombre': 'Fetuccini huancaína con lomo saltado',
      'categoria': 'Pastas y pasta con carne',
      'precio': 30.00,
      'descripcion': 'Fetuccini huancaína acompañado con lomo saltado.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 33,
    },
    {
      'id': 'fetuccini_champinones_bife_lomo',
      'nombre': 'Fetuccini champiñones con bife/lomo',
      'categoria': 'Pastas y pasta con carne',
      'precio': 35.00,
      'descripcion': 'Fetuccini con champiñones acompañado con bife o lomo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 34,
    },
    {
      'id': 'fetuccini_huancaina_pollo',
      'nombre': 'Fetuccini huancaína con pollo',
      'categoria': 'Pastas y pasta con carne',
      'precio': 22.00,
      'descripcion': 'Fetuccini huancaína acompañado con pollo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 35,
    },
    {
      'id': 'fetuccini_pesto_milanesa',
      'nombre': 'Fetuccini pesto con milanesa',
      'categoria': 'Pastas y pasta con carne',
      'precio': 23.00,
      'descripcion': 'Fetuccini al pesto acompañado con milanesa.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 36,
    },
    {
      'id': 'fetuccini_saltado_pollo',
      'nombre': 'Fetuccini saltado de pollo',
      'categoria': 'Pastas y pasta con carne',
      'precio': 20.00,
      'descripcion': 'Fetuccini acompañado con saltado de pollo.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 37,
    },
    {
      'id': 'pizza_americana',
      'nombre': 'Pizza americana',
      'categoria': 'Pizzas artesanales',
      'precio': 15.00,
      'precioFamiliar': 28.00,
      'descripcion': 'Pizza americana artesanal. Precio mediana y familiar.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': true,
      'orden': 38,
    },
    {
      'id': 'pizza_espanola',
      'nombre': 'Pizza española',
      'categoria': 'Pizzas artesanales',
      'precio': 18.00,
      'precioFamiliar': 31.00,
      'descripcion': 'Pizza española artesanal. Precio mediana y familiar.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 39,
    },
    {
      'id': 'pizza_italiana',
      'nombre': 'Pizza italiana',
      'categoria': 'Pizzas artesanales',
      'precio': 16.00,
      'precioFamiliar': 29.00,
      'descripcion': 'Pizza italiana artesanal. Precio mediana y familiar.',
      'imagenUrl': '',
      'disponible': true,
      'destacado': false,
      'orden': 40,
    },
  ];

  static Future<int> cargarProductos() async {
    final batch = _db.batch();

    for (final producto in productos) {
      final id = producto['id'] as String;
      final docRef = _db.collection(collectionName).doc(id);

      final data = Map<String, dynamic>.from(producto);
      data.remove('id');

      data['actualizadoEn'] = FieldValue.serverTimestamp();

      final docActual = await docRef.get();

      if (!docActual.exists) {
        data['creadoEn'] = FieldValue.serverTimestamp();
        data['imagenUrl'] = '';
      } else {
        final actualData = docActual.data();
        final imagenActual = actualData?['imagenUrl'];

        if (imagenActual != null && imagenActual.toString().trim().isNotEmpty) {
          data['imagenUrl'] = imagenActual;
        }
      }

      batch.set(docRef, data, SetOptions(merge: true));
    }

    await batch.commit();
    return productos.length;
  }
}